name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в полночь
  workflow_dispatch:  # Возможность запуска вручную

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: CodeArcadia-fastest  # Убедись, что твой GitHub username

      - name: Push the output
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate snake animation"
          branch: output
